# App name
spring.application.name=student-management

# Database
spring.datasource.url=${DATABASE_URL:jdbc:mysql://localhost:3306/student_db}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root}

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.packagesToScan=com.guide.studentmanagement.controller
springdoc.pathsToMatch=/api/**

# Port
server.port=${PORT:8080}