# App name
spring.application.name=student-management

# MySQL Database Connection
spring.datasource.url=${JDBC_DATABASE_URL:jdbc:mysql://localhost:3306/student_db}
spring.datasource.username=${JDBC_DATABASE_USERNAME:root}
spring.datasource.password=${JDBC_DATABASE_PASSWORD:your_local_password}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.packagesToScan=com.guide.studentmanagement.controller
springdoc.pathsToMatch=/api/**

# Port
server.port=${PORT:8080}